settings.gradle
themepark-service/build.gradle
themepark-service/gradle/wrapper/gradle-wrapper.properties
themepark-service/src/main/java/com/business/themeparkservice/ThemeparkServiceApplication.java
themepark-service/src/main/resources/application.yml
themepark-service/src/test/java/com/business/themeparkservice/ThemeparkServiceApplicationTests.java

✨ feat [#8-themepark] 테마파크 서비스 추가

---

build.gradle
order-service/build.gradle
order-service/gradle/wrapper/gradle-wrapper.properties
order-service/src/main/java/com/sparta/orderservice/OrderServiceApplication.java
order-service/src/main/resources/application.yml
order-service/src/test/java/com/sparta/orderservice/OrderServiceApplicationTests.java
settings.gradle

유레카 서버에 주문 서비스까지 등록되는 것을 확인하였습니다.

✨ feat | 주문 서비스 추가

---

product-service/build.gradle
product-service/src/main/java/com/business/productservice/ProductServiceApplication.java
product-service/src/main/resources/application.yml
settings.gradle

✨ feat [#10-product] 상품 서비스 추가

---

gateway-service/build.gradle
gateway-service/gradle/wrapper/gradle-wrapper.properties
gateway-service/src/main/java/com/business/gatewayservice/GatewayServiceApplication.java
gateway-service/src/main/resources/application.yml
gateway-service/src/test/java/com/business/gatewayservice/GatewayServiceApplicationTests.java
settings.gradle

✨ feat [#9-gateway] gateway 생성

---

product-service/gradle/wrapper/gradle-wrapper.properties

⚙ setting [#10-product] gradle-wrapper.properties 추가

---

product-service/build.gradle
product-service/src/main/java/com/business/productservice/application/dto/request/ReqProductPostDTOApiV1.java
product-service/src/main/java/com/business/productservice/application/dto/response/ResProductPostDTOApiV1.java
product-service/src/main/java/com/business/productservice/common/dto/ResDTO.java
product-service/src/main/java/com/business/productservice/domain/product/entity/ProductEntity.java
product-service/src/main/java/com/business/productservice/domain/product/entity/StockEntity.java
product-service/src/main/java/com/business/productservice/domain/product/vo/ProductType.java
product-service/src/main/java/com/business/productservice/presentation/controller/ProductControllerApiV1.java
product-service/src/test/java/com/business/productservice/ProductServiceApplicationTests.java

- spring-validation, starter-web 의존성 추가
- 상품 생성 엔드포인트 설정 및 더미 데이터 기반 상품 등록 api V1 구현
- 엔티티 파일은 구조 먼저 생성 (추후 구현 예정)
- 공통dto (ResDTO) 생성하여 응답 시 래핑
- 응답 시 product 객체로 감싸서 응답하는 형식으로 구현
- 상품 타입 enum 클래스 작성

✨ feat [#26-product] product controller, dto 구현

---

build.gradle
themepark-service/build.gradle
themepark-service/src/main/java/com/business/themeparkservice/themepark/application/dto/request/ReqThemeparkPostDTOApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/themepark/application/dto/response/ResThemeparkPostDTOApiv1.java
themepark-service/src/main/java/com/business/themeparkservice/themepark/domain/vo/ThemeparkType.java
themepark-service/src/main/java/com/business/themeparkservice/themepark/presentation/controller/ThemeparkControllerApiV1.java
themepark-service/src/test/java/com/business/themeparkservice/httpclient/themeparks.http

- 테마파크 controller 생성
- 테마파크 생성 API 구현
- 테마파크 생성관련 Request, Response Dto 구현
- 테마파크 유형 Enum 클래스 작성
- 생성 API 테스트를 위한 더미데이터 추가코드 작성(ResponseDto 단에 구현)
- 테스트를 위한 httpclient 코드 작성
** 공통응답dto는 공통모듈에서 만들것 같아 추가하지않았습니다.**
- 루트 모듈의 bulid.gradle에 allprojects 부분이 subprojects 내부에 작성되어있어 수정하였습니다
- 입력 코드
------
- 출력 결과

✨ feat [#21-themepark] 테마파크 Create 구현

---

gateway-service/src/main/resources/application.yml
user-service/build.gradle
user-service/src/main/java/com/business/userservice/application/dto/request/ReqAuthJoinDTOApiV1.java
user-service/src/main/java/com/business/userservice/common/dto/ResDTO.java
user-service/src/main/java/com/business/userservice/presentation/controller/AuthControllerApiV1.java

- 회원가입 controller, dto 구현
- 공통 ResDTO 생성

✨ feat [#25-user-join] 회원가입 controller, dto 구현

---

themepark-service/src/main/java/com/business/themeparkservice/themepark/application/dto/request/ReqThemeparkPutDTOApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/themepark/application/dto/response/ResThemeparkPutDTOApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/themepark/presentation/controller/ThemeparkControllerApiV1.java
themepark-service/src/test/java/com/business/themeparkservice/httpclient/themeparks.http

- update api 구현
- response,request dto 구현
- 테스트 코드 작성
- 수정 시 전체값이 출력되도록 구현했습니다.
- 추후, id와 수정한 값 만 출력되도록 구현할 예정입니다.

✨ feat[#21-themepark-update] 테마파크 Update 기능 구현

---

user-service/src/main/java/com/business/userservice/application/dto/request/ReqAuthPostGuestLoginDTOApiV1.java
user-service/src/main/java/com/business/userservice/application/dto/request/ReqAuthPostJoinDTOApiV1.java
user-service/src/main/java/com/business/userservice/application/dto/request/ReqAuthPostLoginDTOApiV1.java
user-service/src/main/java/com/business/userservice/application/dto/response/ResAuthPostGuestLoginDTOApiV1.java
user-service/src/main/java/com/business/userservice/application/dto/response/ResAuthPostLoginDTOApiV1.java
user-service/src/main/java/com/business/userservice/presentation/controller/AuthControllerApiV1.java

- 로그인 controller, dto 구현
- 회원가입 요청 dto 파일명 변경

✨ feat [#25-user-login] 로그인 controller, dto 구현

---

build.gradle
order-service/src/main/java/com/sparta/orderservice/application/dto/request/ReqOrdersPostDtoApiV1.java
order-service/src/main/java/com/sparta/orderservice/application/dto/response/ResDto.java
order-service/src/main/java/com/sparta/orderservice/presentation/controller/OrderControllerApiV1.java

- 주문 생성 controller, dto를 구성하였습니다.
- 'implementation 'jakarta.validation:jakarta.validation-api:3.0.2'
의존성을 root-build-gradle에 추가하였습니다.

✨ feat [#31-order-create] 주문 create  기능 구현

---

product-service/src/main/java/com/business/productservice/application/dto/response/ResProductGetByIdDTOApiV1.java
product-service/src/main/java/com/business/productservice/domain/product/vo/ProductStatus.java
product-service/src/main/java/com/business/productservice/presentation/controller/ProductControllerApiV1.java

- 브랜치명 update 부터 반영하겠습니다!
- controller, 응답 dto 구현했습니다.
- eventEndAt : 일단 max로 처리했습니다

✨ feat [#26-product] 상품 Read controller, dto 구현

---

themepark-service/src/main/java/com/business/themeparkservice/themepark/presentation/controller/ThemeparkControllerApiV1.java
themepark-service/src/test/java/com/business/themeparkservice/httpclient/themeparks.http

- delete api 작성
- 테스트 코드 작성
-입력코드 & 출력

✨ feat[#21-themepark-delete] 테마파크 Delete 기능 구현

---

build.gradle
order-service/build.gradle
order-service/src/main/java/com/sparta/orderservice/application/dto/request/ReqOrderPutDtoApiV1.java
order-service/src/main/java/com/sparta/orderservice/presentation/controller/OrderControllerApiV1.java

- root에 추가한 의존성을 order-service로 옮겼습니다.

✨ feat [#31 order update] 주문 update 기능 구현

---

user-service/src/main/java/com/business/userservice/application/dto/request/ReqUserPutDTOApiV1.java
user-service/src/main/java/com/business/userservice/presentation/controller/UserControllerApiV1.java

✨ feat [#25-user-update] 회원 정보 수정 controller, dto 구현

---

build.gradle
order-service/src/main/java/com/sparta/orderservice/application/dto/request/ReqOrdersPostDtoApiV1.java
order-service/src/main/java/com/sparta/orderservice/application/dto/response/ResOrderGetDtoApiV1.java
order-service/src/main/java/com/sparta/orderservice/presentation/controller/OrderControllerApiV1.java

- 주문 조회 기능을 구현하였습니다.
- response 데이터에 상품이라고 명시된것을 주문으로 수정하였습니다.
- build.gralde 수정사항 반영 안된것 수정하였습니다.

✨ feat [#31-order-read] 주문 read 기능 구현

---

product-service/src/main/java/com/business/productservice/application/dto/request/ReqProductPutDTOApiV1.java
product-service/src/main/java/com/business/productservice/presentation/controller/ProductControllerApiV1.java

✨ feat [#26-product-update] 상품 수정 controller, dto 구현

---

themepark-service/src/main/java/com/business/themeparkservice/hashtag/application/dto/response/ResHashtagGetByIdDTOApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/hashtag/presentation/controller/HashtagControllerApiV1.java
themepark-service/src/test/java/com/business/themeparkservice/httpclient/hashtags.http

- Read api 추가
- ResponseDto 추가
- 테스트 코드 작성

✨ feat [#22-hashtag-read] 해시태그 Read 기능 구현

---

order-service/src/main/java/com/sparta/orderservice/presentation/controller/OrderControllerApiV1.java

- HttpStatus create 관련된 api 는 created 반환으로 수정하였습니다.
- delete는 별도의 res, req dto를 생성하지 않았습니다.

✨ feat [#31-order-delete] 주문 delete 기능 구현

---

themepark-service/src/main/java/com/business/themeparkservice/hashtag/application/dto/request/ReqHashtagPutDTOApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/hashtag/application/dto/response/ResHashtagGetByIdDTOApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/hashtag/application/dto/response/ResHashtagPutDTOApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/hashtag/presentation/controller/HashtagControllerApiV1.java
themepark-service/src/test/java/com/business/themeparkservice/httpclient/hashtags.http

- Update api 추가
- Update api 관련 request,response Dto 추가
- 테스트 코드 작성

✨ feat [#22-hashtag-update] 해시태그 Update 기능 구현

---

product-service/src/main/java/com/business/productservice/presentation/controller/ProductControllerApiV1.java

✨ feat [#26-product-delete] 상품 삭제 controller 구현

---

themepark-service/src/main/java/com/business/themeparkservice/hashtag/presentation/controller/HashtagControllerApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/themepark/presentation/controller/ThemeparkControllerApiV1.java
themepark-service/src/test/java/com/business/themeparkservice/httpclient/hashtags.http

✨ feat [#22-hashtag-delete] 해시태그 Delete 기능 구현

---

user-service/build.gradle
user-service/src/main/java/com/business/userservice/application/dto/response/ResUserGetByIdDTOApiV1.java
user-service/src/main/java/com/business/userservice/application/dto/response/ResUserGetDTOApiV1.java
user-service/src/main/java/com/business/userservice/domain/user/entity/UserEntity.java
user-service/src/main/java/com/business/userservice/domain/user/vo/RoleType.java
user-service/src/main/java/com/business/userservice/presentation/controller/UserControllerApiV1.java

- db 관련 의존성 추가
- 회원 아이디 기반 회원 정보 조회 controller, dto 구현
- 회원 정보 리스트 조회 controller, dto 구현

✨ feat [#25-user-read] 회원 정보 조회 controller, dto 구현

---

gateway-service/src/main/resources/application.yml
themepark-service/src/main/java/com/business/themeparkservice/waiting/application/dto/request/ReqWaitingPostDTOApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/application/dto/response/ResWaitingPostDTOApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/common/dto/ResDTO.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/domain/vo/WaitingStatus.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/presentation/controller/WaitingControllerApiV1.java
themepark-service/src/test/java/com/business/themeparkservice/httpclient/waitings.http

- controller 생성
- create api 구현
- create api 관련 request,response Dto 구현
- waiting status enum 생성
- gateway waiting endpoint 추가
- 테스트 코드 작성

✨ feat [#22-waiting-create] 테마파크대기 Create 기능 구현

---

product-service/src/main/java/com/business/productservice/application/dto/request/ReqStockDecreasePatchDTOApiV1.java
product-service/src/main/java/com/business/productservice/application/dto/request/ReqStockRestorePatchDTOApiV1.java
product-service/src/main/java/com/business/productservice/presentation/controller/StockControllerApiV1.java

- 재고 차감, 복구 엔드포인트 설정
- 주문 서비스 요청 시 실행되는 api입니다.

✨ feat [#47-product-stock-update] 상품 재고 복구, 차감 controller 및 dto 구현

---

user-service/src/main/java/com/business/userservice/application/dto/request/ReqUserDeleteDTOApiV1.java
user-service/src/main/java/com/business/userservice/presentation/controller/UserControllerApiV1.java

- 회원 탈퇴 controller, dto 구현
- 회원 블랙리스트 설정 controller, dto  구현

✨ feat [#25-user-restriction] 회원 탈퇴, 블랙리스트 설정 controller, dto 구현

---

themepark-service/src/main/java/com/business/themeparkservice/waiting/application/dto/response/ResWaitingGetByIdDTOApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/application/dto/response/ResWaitingPostDoneDTOApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/presentation/controller/WaitingControllerApiV1.java
themepark-service/src/test/java/com/business/themeparkservice/httpclient/waitings.http

- 대기완료 api 구현
- 대기완료 api 관련 response Dto 구현
- 테스트 코드 작성

✨ feat [#22-waiting-done] 테마파크 대기완료 기능 구현

---

order-service/src/main/java/com/sparta/orderservice/application/dto/request/ReqPaymentPostDtoApiV1.java
order-service/src/main/java/com/sparta/orderservice/application/dto/request/ReqPaymentPutDtoApiV1.java
order-service/src/main/java/com/sparta/orderservice/presentation/controller/PaymentControllerApiV1.java

✨ feat [#53-payment-update] 결제 update 기능 구현

---

order-service/src/main/java/com/sparta/orderservice/application/dto/request/ReqPaymentPostDtoApiV1.java
order-service/src/main/java/com/sparta/orderservice/presentation/controller/PaymentControllerApiV1.java

✨ feat [#53-payment-create] 결제 create 기능 구현

---

themepark-service/src/main/java/com/business/themeparkservice/waiting/presentation/controller/WaitingControllerApiV1.java
themepark-service/src/test/java/com/business/themeparkservice/httpclient/waitings.http

✨ feat [#22-waiting-delete] 테마파크대기 Delete 기능 구현

---

gateway-service/build.gradle
gateway-service/src/main/resources/application.yml
user-service/build.gradle

- 공통으로 관리하기 위한 각 도메인 Swagger 설정

⚙ setting [#59-gateway-swagger] Swagger 설정

---

product-service/build.gradle
product-service/src/main/java/com/business/productservice/application/dto/request/ReqProductPutDTOApiV1.java
product-service/src/main/java/com/business/productservice/application/dto/response/ResProductGetDTOApiV1.java
product-service/src/main/java/com/business/productservice/presentation/controller/ProductControllerApiV1.java

- ProductEntity 리스트를 임시 생성하여 PageImpl로 페이징 형식 유지
- 실제 Repository 연동 전 테스트용 응답 구조 구현
- ProductPage, Product 내부 정적 클래스 구성
- 하드코딩된 from() 메서드 구현
- 상품 수정 dto 변경 사항
- 요청 dto 오타 수정 Post > Put
- 요청 dto에 상태변경 필드 추가
- 의존성 추가: 아직 db 결정되지 않아서 일단 h2로 넣어놓고 jpa 잘 돌아가도록 해놨습니다

✨ feat [#26-product-read] 상품 전체 조회 및 검색 controller, dto 구현

---

order-service/src/main/java/com/sparta/orderservice/application/dto/response/ResOrdersGetByIdDtoApiV1.java
order-service/src/main/java/com/sparta/orderservice/presentation/controller/OrderControllerApiV1.java

- 우선 null 값을 보내게 설정하였습니다.
- orders, orders 이름이 겹쳐 ordersList로 수정하였습니다.

✨ feat [#/31-order-get-userId] 주문 get by userid 기능 구현

---

themepark-service/build.gradle
themepark-service/src/main/java/com/business/themeparkservice/themepark/application/dto/response/ResThemeparkGetDTOApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/themepark/domain/entity/ThemeparkEntity.java
themepark-service/src/main/java/com/business/themeparkservice/themepark/presentation/controller/ThemeparkControllerApiV1.java
themepark-service/src/test/java/com/business/themeparkservice/httpclient/themeparks.http

- search api 구현
- search api 관련 resposneDto 생성
- ThemeparkEntity 생성
- 의존성 연결
- 테스트 코드 작성
-  엔드포인트
---
- 결과

✨ feat[#21-themepark-search] 테마파크 Search 기능 구현

---

user-service/src/main/java/com/business/userservice/application/dto/response/ResUserGetByIdDTOApiV1.java
user-service/src/main/java/com/business/userservice/presentation/controller/AuthControllerApiV1.java
user-service/src/main/java/com/business/userservice/presentation/controller/UserControllerApiV1.java

- 유저 조회 응답 dto 필드값 변경 (컴포지션 패턴 적용)
- 회원 탈퇴 Delete 매핑에서 Post 매핑으로 변경
- RequiredArgsConstructor 어노테이션 설정

🔨 refactor [#66-user] User 관련 Controller, DTO 피드백 적용

---

themepark-service/src/main/java/com/business/themeparkservice/waiting/application/dto/response/ResWaitingGetDTOApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/domain/entity/WaitingEntity.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/presentation/controller/WaitingControllerApiV1.java
themepark-service/src/test/java/com/business/themeparkservice/httpclient/waitings.http

- search api 구현
- search api 관련 resposneDto 생성
- WaitingEntity 생성
- 테스트 코드 작성
- 엔드포인트
---
- 결과

✨ feat [#23-waiting-search] 테마파크대기열 Search 기능 구현

---

build.gradle
themepark-service/src/test/java/com/business/themeparkservice/themepark/presentation/controller/ThemeparkControllerApiV1Test.java

- post,get 테스트코드 작성
- bulid.gradle 테스트 통과부분 주석처리
*코드 수정부분은 리팩토링으로 작성하여 올릴예정입니다.*

🎈 test [#69-themepark] 테마파크 테스트코드 작성

---

user-service/src/main/java/com/business/userservice/application/dto/request/ReqAuthPostJoinDTOApiV1.java
user-service/src/main/java/com/business/userservice/application/dto/request/ReqAuthPostLoginDTOApiV1.java
user-service/src/main/java/com/business/userservice/application/dto/request/ReqUserPutDTOApiV1.java
user-service/src/main/resources/application-dev.yml
user-service/src/main/resources/application.yml
user-service/src/test/java/com/business/userservice/user/presentation/controller/AuthControllerApiV1Test.java
user-service/src/test/java/com/business/userservice/user/presentation/controller/UserControllerApiV1Test.java

- Auth Controller 테스트 코드 작성
- User Controller 테스트 코드 작성
- dev용 yml 파일 분리

🎈 test [#73-user] 회원 관련 테스트 코드 작성

---

themepark-service/src/main/java/com/business/themeparkservice/themepark/application/dto/request/ReqThemeparkPostDTOApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/themepark/application/dto/request/ReqThemeparkPutDTOApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/themepark/application/dto/response/ResThemeparkGetByIdDTOApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/themepark/application/dto/response/ResThemeparkGetDTOApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/themepark/application/dto/response/ResThemeparkPostDTOApiv1.java
themepark-service/src/main/java/com/business/themeparkservice/themepark/application/dto/response/ResThemeparkPutDTOApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/themepark/presentation/controller/ThemeparkControllerApiV1.java
themepark-service/src/main/resources/application-dev.yml
themepark-service/src/main/resources/application.yml
themepark-service/src/test/java/com/business/themeparkservice/httpclient/themeparks.http

- request,response dto 수정
- application.yml 개발버전 분리
- 테스트코드 수정

🔨 refactor[#78-themepark] 테마파크 코드 리팩토링

---

themepark-service/src/test/java/com/business/themeparkservice/themepark/presentation/controller/ThemeparkControllerApiV1Test.java

🎈 test [#71-themepark] 테마파크 테스트코드 작성

---

themepark-service/src/main/java/com/business/themeparkservice/hashtag/presentation/controller/HashtagControllerApiV1.java
themepark-service/src/test/java/com/business/themeparkservice/hashtag/presentation/HashtagControllerApiV1Test.java
themepark-service/src/test/java/com/business/themeparkservice/hashtag/presentation/controller/HashtagControllerApiV1Test.java

🎈 test [#71-themepark] 테마파크 해시태그 테스트코드 작성

---

themepark-service/build.gradle
themepark-service/src/main/java/com/business/themeparkservice/hashtag/presentation/controller/HashtagControllerApiV1.java
themepark-service/src/test/java/com/business/themeparkservice/hashtag/presentation/HashtagControllerApiV1Test.java
themepark-service/src/test/java/com/business/themeparkservice/hashtag/presentation/controller/HashtagControllerApiV1Test.java
themepark-service/src/test/java/com/business/themeparkservice/waiting/presentation/controller/WaitingControllerApiV1Test.java

🎈 test  [#71-themepark-waiting] 테마파크 대기열 테스트코드 작성

---

order-service/build.gradle
order-service/src/main/java/com/sparta/orderservice/application/dto/response/ResOrderGetDtoApiV1.java
order-service/src/main/java/com/sparta/orderservice/application/dto/response/ResOrdersGetByIdDtoApiV1.java

- resDto 데이터를 payment로 객체화시켜 orederResDto를 반환하게 해주었습니다.

🔨 refactor [/#31-order] orderResDto 리팩토링

---

product-service/src/main/java/com/business/productservice/application/dto/request/ReqStockDecreasePostDTOApiV1.java
product-service/src/main/java/com/business/productservice/application/dto/request/ReqStockRestorePostDTOApiV1.java
product-service/src/main/java/com/business/productservice/presentation/controller/ProductControllerApiV1.java
product-service/src/test/java/com/business/productservice/product/presentation/controller/ProductControllerApiV1Test.java

- 테스트 코드 작성했습니다.
- dto 명 put > post 로 변경
- pathvariable name 명시 (필요없을 경우 제외할 예정)

🎈 test [#76-product-stock] 상품 테스트 코드 작성

---

gateway-service/src/main/resources/application.yml

⚙ setting [#90-gateway-swagger] Swagger 문서 통합 설정

---

order-service/build.gradle
order-service/src/main/resources/application-dev.yml
order-service/src/test/java/com/sparta/orderservice/presentation/controller/OrderControllerApiV1Test.java
order-service/src/test/java/com/sparta/orderservice/presentation/controller/PaymentControllerApiV1Test.java

⚙ setting [ /#74-order-swagger] 테스트 코드 스웨거 문서화

---

themepark-service/build.gradle

📄 docs [#89-themepark] 테마파크 swagger 자동 문서화기능 일부수정

---

product-service/build.gradle
product-service/src/test/java/com/business/productservice/product/presentation/controller/ProductControllerApiV1Test.java

- testProductPostSuccess()에 .andDo()추가
- API 문서 자동 생성을 위한 RestDocs + Swagger 연동 작업
- tag: Product v1 설정
- 의존성 추가

📄 docs [#88-product] 상품 서비스 API RestDocs 문서화 및 스웨거 자동화 적용 

---

order-service/src/main/resources/application-dev.yml
order-service/src/test/java/com/sparta/orderservice/presentation/controller/OrderControllerApiV1Test.java
order-service/src/test/java/com/sparta/orderservice/presentation/controller/PaymentControllerApiV1Test.java

✏️ fix  [/#74-test-swagger] 파일 오류 수정

---

user-service/build.gradle
user-service/src/test/java/com/business/userservice/user/presentation/controller/AuthControllerApiV1Test.java
user-service/src/test/java/com/business/userservice/user/presentation/controller/UserControllerApiV1Test.java

⚙ setting [#97 user swagger] 테스트 코드와 Swagger 연동

---

themepark-service/build.gradle
themepark-service/src/main/java/com/business/themeparkservice/themepark/domain/entity/ThemeparkEntity.java
themepark-service/src/main/java/com/business/themeparkservice/themepark/domain/repository/ThemeparkRepository.java
themepark-service/src/main/java/com/business/themeparkservice/themepark/infastructure/ThemeparkJpaRepository.java
themepark-service/src/main/resources/application-dev.yml

- postgresql 의존성 추가
- 테마파크 entity 구현 , BaseEntity 연결
- 테마파크 repository 구현
- postgresql 연동을위한 application-dev.yml 수정
- common repository 의존성 수정
*postgresql 로컬으로 연동완료했습니다.*

✨ feat [#100 themepark] 테마파크 entity,repository 추가

---

themepark-service/src/main/java/com/business/themeparkservice/hashtag/domain/HashtagRepository.java
themepark-service/src/main/java/com/business/themeparkservice/hashtag/domain/entity/HashtagEntity.java
themepark-service/src/main/java/com/business/themeparkservice/hashtag/domain/repository/HashtagRepository.java
themepark-service/src/main/java/com/business/themeparkservice/hashtag/infastructure/persistence/hashtag/HashtagJpaRepository.java
themepark-service/src/main/java/com/business/themeparkservice/themepark/infastructure/persistence/themepark/ThemeparkJpaRepository.java

- entity 추가
- repository 추가
- 패키지 경로 수정
*postgresql 로컬로 연결진행했습니다!*
*baseEntity 트러블슈팅 완료되는대로 연결할 예정입니다!*

✨ feat [#100-themepark] 테마파크 해시태그 entity,repository 추가

---

product-service/build.gradle
product-service/src/main/java/com/business/productservice/domain/product/entity/ProductEntity.java
product-service/src/main/resources/application-dev.yml

- application-dev.yml 에 db 설정
- 상품 엔티티 생성
- 루트 build.gradle에 있던 의존성 각 서비스로 이동

⚙ setting [#104-product] 상품 엔티티 생성, 의존성 추가, db 설정

---

themepark-service/build.gradle
themepark-service/src/main/java/com/business/themeparkservice/hashtag/domain/entity/HashtagEntity.java
themepark-service/src/main/java/com/business/themeparkservice/themepark/domain/entity/ThemeparkEntity.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/domain/entity/WaitingEntity.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/domain/repository/WaitingRepository.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/infastructure/persistence/waiting/WaitingJpaRepository.java

- entity 추가, base entity 상속추가
- base entity 수정으로인한 의존성 변경
- repository 추가

✨ feat[#100-themepark] 테마파크 대기열 entity,repository 추가

---

eureka-server/build.gradle
gateway-service/build.gradle
user-service/build.gradle

- 루트 build.gradle에 있던 공통 설정을 각 모듈로 분리

🔨 refactor [#109-gateway-eureka-user] build.gradle 설정

---

themepark-service/src/main/java/com/business/themeparkservice/hashtag/application/dto/response/ResHashtagGetByIdDTOApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/hashtag/application/dto/response/ResHashtagPutDTOApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/hashtag/application/service/HashtagServiceApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/hashtag/application/service/HashtagServiceImplApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/hashtag/domain/entity/HashtagEntity.java
themepark-service/src/main/java/com/business/themeparkservice/hashtag/presentation/controller/HashtagControllerApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/themepark/application/service/ThemeparkServiceImplApiV1.java
themepark-service/src/test/java/com/business/themeparkservice/httpclient/hashtags.http

- service 로직추가
- response dto 수정
- 엔티티 update() 로직추가

✨ feat[#124 hashtag update] 해시태그 수정기능 구현

---

user-service/src/main/java/com/business/userservice/application/dto/request/ReqAuthPostLoginDTOApiV1.java
user-service/src/main/java/com/business/userservice/application/dto/response/ResAuthPostLoginDTOApiV1.java
user-service/src/main/java/com/business/userservice/application/service/UserDetailsServiceImpl.java
user-service/src/main/java/com/business/userservice/domain/user/entity/UserEntity.java
user-service/src/main/java/com/business/userservice/infrastructure/auth/JwtFilter.java
user-service/src/main/java/com/business/userservice/infrastructure/auth/JwtUtil.java
user-service/src/main/java/com/business/userservice/infrastructure/auth/LoginFilter.java
user-service/src/main/java/com/business/userservice/infrastructure/auth/UserDetailsImpl.java
user-service/src/main/java/com/business/userservice/infrastructure/config/SecurityConfig.java
user-service/src/main/java/com/business/userservice/presentation/controller/AuthControllerApiV1.java
user-service/src/main/resources/application-dev.yml

- 로그인 DTO에 Getter 추가
- UserEntity에 블랙리스트 여부 필드 추가
- yml 파일에 시크릿 키 설정 및 DB 설정
- UserDetails와 UserDetailsService 구현
- JWT 생성 및 검증, JWT 필터 구현
- 컨트롤러에 있는 로그인 엔드 포인트를 제거하고 로그인 필터 생성

✨ feat [#120-user-login] 로그인 기능 구현

---

themepark-service/src/main/java/com/business/themeparkservice/hashtag/application/dto/response/ResHashtagGetDTOApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/hashtag/application/service/HashtagServiceApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/hashtag/application/service/HashtagServiceImplApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/hashtag/domain/repository/HashtagRepository.java
themepark-service/src/main/java/com/business/themeparkservice/hashtag/infastructure/persistence/hashtag/HashtagJpaRepository.java
themepark-service/src/main/java/com/business/themeparkservice/hashtag/presentation/controller/HashtagControllerApiV1.java
themepark-service/src/test/java/com/business/themeparkservice/ThemeparkServiceApplicationTests.java
themepark-service/src/test/java/com/business/themeparkservice/httpclient/hashtags.http

- service 로직추가
- response dto 수정
- 테스트코드 수정

✨ feat [#119-hashtag-search] 해시태그 검색 기능 구현

---

themepark-service/src/main/java/com/business/themeparkservice/themepark/application/dto/response/ResThemeparkGetByIdDTOApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/themepark/application/service/ThemeparkServiceApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/themepark/application/service/ThemeparkServiceImplApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/themepark/domain/entity/ThemeparkHashtagEntity.java
themepark-service/src/main/java/com/business/themeparkservice/themepark/domain/repository/ThemeparkHashtagRepository.java
themepark-service/src/main/java/com/business/themeparkservice/themepark/presentation/controller/ThemeparkControllerApiV1.java
themepark-service/src/test/java/com/business/themeparkservice/httpclient/themeparks.http

- service 로직추가
- response dto 수정
- 테스트코드 수정

✨ feat [#118-themepark-read] 테마파크 단건조회 기능 구현

---

product-service/build.gradle
product-service/src/main/java/com/business/productservice/application/dto/response/ResProductGetByIdDTOApiV1.java
product-service/src/main/java/com/business/productservice/application/exception/ProductExceptionCode.java
product-service/src/main/java/com/business/productservice/application/service/ProductServiceApiV1.java
product-service/src/main/java/com/business/productservice/application/service/ProductServiceImplApiV1.java
product-service/src/main/java/com/business/productservice/presentation/controller/ProductControllerApiV1.java
product-service/src/test/java/com/business/productservice/product/presentation/controller/ProductControllerApiV1Test.java
product-service/src/test/resources/httpclient/product.http

- 비즈니스 로직 구현
- 상품 예외 코드 생성
- 상품 없을 경우 예외 처리
- http client test 완료
- 의존성 추가 (루트 제거 예정)
- 테스트 코드 수정 : 파라미터 값인 uuid가 실제 db에 없어서 예외 처리 됨 > 테스트 실패. 따라서 하드코딩된 응답dto 생성 후 리턴하는 코드 추가

✨ feat  [#122-product-read] 상품 단건 조회 기능 구현

---

user-service/src/main/java/com/business/userservice/application/dto/response/ResUserGetByIdDTOApiV1.java
user-service/src/main/java/com/business/userservice/application/dto/response/ResUserGetDTOApiV1.java
user-service/src/main/java/com/business/userservice/application/service/UserServiceApiV1.java
user-service/src/main/java/com/business/userservice/application/service/UserServiceImplApiV1.java
user-service/src/main/java/com/business/userservice/domain/user/repository/UserRepository.java
user-service/src/main/java/com/business/userservice/infrastructure/persistence/user/UserJpaRepository.java
user-service/src/main/java/com/business/userservice/presentation/controller/UserControllerApiV1.java

- 아이디 기반 회원 정보 조회
- 회원 정보 리스트 조회(검색)

✨ feat [#130-user-read] 회원 정보 조회 구현

---

product-service/src/main/java/com/business/productservice/application/dto/request/ReqProductPutDTOApiV1.java
product-service/src/main/java/com/business/productservice/application/dto/response/ResProductPutDTOApiV1.java
product-service/src/main/java/com/business/productservice/application/service/ProductServiceApiV1.java
product-service/src/main/java/com/business/productservice/application/service/ProductServiceImplApiV1.java
product-service/src/main/java/com/business/productservice/domain/product/entity/ProductEntity.java
product-service/src/main/java/com/business/productservice/domain/product/entity/StockEntity.java
product-service/src/main/java/com/business/productservice/presentation/controller/ProductControllerApiV1.java
product-service/src/test/java/com/business/productservice/product/presentation/controller/ProductControllerApiV1Test.java
product-service/src/test/resources/httpclient/product.http

- 상품 정보 수정 비즈니스 로직 구현
- 예외처리 구현
- 상품 limitQuantity 변경 시 재고 stock 필드도 함께 변경되도록 상품 엔티티 내부에서 조건문으로 구현
- http client test 완료

✨ feat [#132-product-update] 상품 정보 수정 기능 구현

---

themepark-service/src/main/java/com/business/themeparkservice/themepark/application/dto/response/ResThemeparkPutDTOApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/themepark/application/service/ThemeparkServiceApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/themepark/application/service/ThemeparkServiceImplApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/themepark/domain/entity/ThemeparkEntity.java
themepark-service/src/main/java/com/business/themeparkservice/themepark/presentation/controller/ThemeparkControllerApiV1.java
themepark-service/src/test/java/com/business/themeparkservice/httpclient/themeparks.http

- service 로직추가
- entity 에 수정로직 추가
- response dto 수정
- 테스트코드 수정
- 입력
- 출력

✨ feat [#134-themepark-update] 테마파크 수정 기능 구현

---

themepark-service/build.gradle
themepark-service/src/main/java/com/business/themeparkservice/themepark/application/service/ThemeparkServiceImplApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/application/dto/request/ReqWaitingPostDTOApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/application/dto/response/ResWaitingPostDTOApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/application/service/WaitingServiceApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/application/service/WaitingServiceImplApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/domain/entity/WaitingEntity.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/domain/repository/WaitingRepository.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/infastructure/persistence/waiting/WaitingJpaRepository.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/presentation/controller/WaitingControllerApiV1.java
themepark-service/src/test/java/com/business/themeparkservice/httpclient/waitings.http

- service 로직추가
- entity 에 생성로직 추가
- request,response dto 수정
- 테스트코드 수정
- 대기열 생성 시 이전에 생성된 대기정보 확인
- common repository 버전 업데이트

✨ feat[#145-waiting-create] 대기열 생성 기능 구현

---

user-service/build.gradle
user-service/src/main/java/com/business/userservice/application/dto/request/ReqUserDeleteDTOApiV1.java
user-service/src/main/java/com/business/userservice/application/dto/request/ReqUserPutDTOApiV1.java
user-service/src/main/java/com/business/userservice/application/service/UserServiceApiV1.java
user-service/src/main/java/com/business/userservice/application/service/UserServiceImplApiV1.java
user-service/src/main/java/com/business/userservice/domain/user/entity/UserEntity.java
user-service/src/main/java/com/business/userservice/presentation/controller/UserControllerApiV1.java

- 회원 탈퇴 요청 시 password를 비교하여 일치하는 경우 soft delete 진행
- dirty checking을 통한 회원 정보 수정 구현

✨ feat [#149-user-update-delete] 회원  탈퇴 및 회원 정보 수정 구현

---

themepark-service/src/main/java/com/business/themeparkservice/waiting/application/dto/response/ResWaitingGetByIdDTOApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/application/service/WaitingServiceApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/application/service/WaitingServiceImplApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/domain/entity/WaitingEntity.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/domain/repository/WaitingRepository.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/infastructure/persistence/waiting/WaitingJpaRepository.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/presentation/controller/WaitingControllerApiV1.java
themepark-service/src/test/java/com/business/themeparkservice/httpclient/waitings.http

- 대기 생성기능 코드수정
- repository 수정
- service 단건조회기능 추가
- 조회 시 남은 대기자 정보 업데이트되도록 구현
- 테스트코드 수정

✨ feat[#150-waiting-read] 대기 단건조회 기능 구현

---

themepark-service/src/main/java/com/business/themeparkservice/waiting/application/dto/response/ResWaitingPostDoneDTOApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/application/service/WaitingServiceApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/application/service/WaitingServiceImplApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/domain/entity/WaitingEntity.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/presentation/controller/WaitingControllerApiV1.java
themepark-service/src/test/java/com/business/themeparkservice/httpclient/waitings.http

- service 추가
- 대기완료 상태 업데이트 메소드 추가
- 테스트코드 수정

✨ feat[#155-waiting-done] 대기 완료 기능 구현

---

themepark-service/src/main/java/com/business/themeparkservice/waiting/application/dto/response/ResWaitingPostCancelDTOApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/application/dto/response/ResWaitingPostDoneDTOApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/application/service/WaitingServiceApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/application/service/WaitingServiceImplApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/domain/entity/WaitingEntity.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/presentation/controller/WaitingControllerApiV1.java
themepark-service/src/test/java/com/business/themeparkservice/httpclient/waitings.http

- service 구현
- 대기취소 상태 적용 메소드 구현
- 테스트코드 수정

✨ feat[#155-waiting-cancel] 대기 취소 기능 구현

---

themepark-service/build.gradle
themepark-service/src/main/java/com/business/themeparkservice/waiting/application/service/WaitingServiceApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/application/service/WaitingServiceImplApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/domain/entity/WaitingEntity.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/domain/repository/WaitingRepository.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/presentation/controller/WaitingControllerApiV1.java
themepark-service/src/test/java/com/business/themeparkservice/httpclient/waitings.http

- service 로직 구현
- 대기삭제 시 취소된 대기만 삭제가능하도록 구현.
- repository 로직 구현
- build.gradle 의존성 수정완료

✨ feat[#159-waiting-delete] 대기 삭제 기능 구현

---

themepark-service/build.gradle
themepark-service/src/main/java/com/business/themeparkservice/waiting/application/dto/response/ResWaitingGetDTOApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/application/service/WaitingServiceApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/application/service/WaitingServiceImplApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/domain/entity/WaitingEntity.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/domain/repository/WaitingRepository.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/infastructure/persistence/waiting/WaitingJpaRepository.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/presentation/controller/WaitingControllerApiV1.java
themepark-service/src/test/java/com/business/themeparkservice/httpclient/waitings.http

- service 로직 구현
- repository 로직 구현
- 테스트코드 수정

✨ feat [#150-waiting-search] 대기 검색 기능 구현

---

docker-compose.yml
init.sql
themepark-service/src/main/resources/application-dev.yml

- postgres docker-compose.yml 설정
- 스키마 분리 설정
- 스키마 설정 및 엔티티 생성테스트 진행
실행방법
1. postgresql docker로 실행! (간편실행방법)
---
2. postgres 연결설정
---
3. 본인의 서비스 application에 스키마 설정! (*각 서비스 별로 스키마 생성해두었습니다!*)

✨ feat [#163-docker-compose] 데이터베이스 docker 연결

---

gateway-service/build.gradle
gateway-service/src/main/java/com/business/gatewayservice/infrastructure/config/SecurityConfig.java
gateway-service/src/main/java/com/business/gatewayservice/infrastructure/filter/CustomPreFilter.java
gateway-service/src/main/resources/application.yml

- jwt 버전 변경 및 lombok과 security 의존성 추가
- jwt 토큰 검증 및 사용자 정보 추출 기능 구현
@RequestHeader("X-User-Id")을 사용하여 로그인된 사용자의 id 값을 받아올 수 있습니다.
잘못된 토큰일 경우

✨ feat [#169-gateway-jwt] JWT 인증 및 인가 필터 추가

---

user-service/src/main/java/com/business/userservice/UserServiceApplication.java
user-service/src/main/java/com/business/userservice/application/exception/AuthExceptionCode.java
user-service/src/main/java/com/business/userservice/application/exception/UserExceptionCode.java
user-service/src/main/java/com/business/userservice/application/service/AuthServiceImplApiV1.java
user-service/src/main/java/com/business/userservice/application/service/UserServiceImplApiV1.java
user-service/src/main/java/com/business/userservice/infrastructure/jwt/JwtAuthenticationFilter.java
user-service/src/main/java/com/business/userservice/infrastructure/security/UserDetailsServiceImpl.java

Auth와 User 관련 예외 로직에 CustomException 적용

🔨 refactor [#171-user-exception] CustomException 적용

---

gateway-service/build.gradle
gateway-service/src/main/java/com/business/gatewayservice/application/exception/GatewayExceptionCode.java
gateway-service/src/main/java/com/business/gatewayservice/infrastructure/filter/CustomPreFilter.java

- gateway 예외 코드 작성 및 CustomException 적용

🔨 refactor [#177-gateway-exception] CustomException 적용

---

user-service/build.gradle
user-service/src/main/java/com/business/userservice/presentation/controller/UserControllerApiV1.java

- common 버전을 0.0.9로 설정합니다.
- 각 api에 @ApiPermission을 이용한 권한 설정을 합니다. 아래 사진을 참고해주세요.
권한이 없는 경우

✨ feat  [#182-user-role] User API에 권한 설정

---

gateway-service/build.gradle
gateway-service/src/main/java/com/business/gatewayservice/infrastructure/filter/CustomPreFilter.java
user-service/build.gradle
user-service/src/main/java/com/business/userservice/application/dto/request/ReqAuthPostLoginDTOApiV1.java
user-service/src/test/java/com/business/userservice/httpClient/auth.http
user-service/src/test/java/com/business/userservice/httpClient/user.http
user-service/src/test/java/com/business/userservice/httpclient/auth.http
user-service/src/test/java/com/business/userservice/user/presentation/controller/AuthControllerApiV1Test.java

- AuthController 테스트 코드 수정
- User 및 Auth httpClient 테스트 코드 작성
- jwt 의존성 수정
- Swagger jwt 인증 제외

🎈 test [#188-user] User 관련 테스트 코드 수정

---

user-service/build.gradle
user-service/src/main/java/com/business/userservice/application/dto/request/ReqUserPostDeleteDTOApiV1.java
user-service/src/main/java/com/business/userservice/application/dto/response/ResAuthGetRefreshDTOApiV1.java
user-service/src/main/java/com/business/userservice/application/service/UserServiceApiV1.java
user-service/src/main/java/com/business/userservice/application/service/UserServiceImplApiV1.java
user-service/src/main/java/com/business/userservice/domain/user/vo/RoleType.java
user-service/src/main/java/com/business/userservice/presentation/controller/AuthControllerApiV1.java
user-service/src/main/java/com/business/userservice/presentation/controller/UserControllerApiV1.java
user-service/src/test/java/com/business/userservice/user/presentation/controller/AuthControllerApiV1Test.java
user-service/src/test/java/com/business/userservice/user/presentation/controller/UserControllerApiV1Test.java

- 회원 역할 이름 admin -> manager로 수정
- refresh 응답 dto 생성
- refresh 테스트 구현
- delete 요청 dto 클래스 이름 변경

🔨 refactor [#190-user] 회원 역할 이름 수정, refresh 응답 dto, test 생성

---

user-service/src/main/java/com/business/userservice/application/dto/request/JoinRequest.java
user-service/src/main/java/com/business/userservice/application/dto/request/ReqAuthPostManagerJoinDTOApiV1.java
user-service/src/main/java/com/business/userservice/application/dto/response/ResAuthPostManagerJoinDTOApiV1.java
user-service/src/main/java/com/business/userservice/application/service/AuthServiceApiV1.java
user-service/src/main/java/com/business/userservice/application/service/AuthServiceImplApiV1.java
user-service/src/main/java/com/business/userservice/application/service/UserServiceApiV1.java
user-service/src/main/java/com/business/userservice/application/service/UserServiceImplApiV1.java
user-service/src/main/java/com/business/userservice/domain/user/entity/UserEntity.java
user-service/src/main/java/com/business/userservice/presentation/controller/AuthControllerApiV1.java
user-service/src/main/java/com/business/userservice/presentation/controller/UserControllerApiV1.java
user-service/src/test/java/com/business/userservice/httpClient/auth.http

- 매니저 생성 기능 추가
- 블랙리스트 기능 추가
매니저 생성
블랙리스트 설정
블랙리스트 해제

✨ feat [#199-user] 매니저 생성 및 블랙리스트 기능 구현

---

order-service/src/main/java/com/sparta/orderservice/payment/application/service/PaymentService.java

✏️ fix  [오류 수정]

---

themepark-service/build.gradle
themepark-service/src/main/java/com/business/themeparkservice/themepark/presentation/controller/ThemeparkControllerApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/application/dto/request/ReqWaitingPostDTOApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/application/dto/response/ResWaitingGetByIdDTOApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/application/dto/response/ResWaitingGetDTOApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/application/dto/response/ResWaitingPostCancelDTOApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/application/dto/response/ResWaitingPostDTOApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/application/dto/response/ResWaitingPostDoneDTOApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/application/service/WaitingServiceApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/application/service/WaitingServiceImplApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/domain/entity/WaitingEntity.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/domain/repository/WaitingRepository.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/presentation/controller/WaitingControllerApiV1.java
themepark-service/src/test/java/com/business/themeparkservice/httpclient/waitings.http
themepark-service/src/test/java/com/business/themeparkservice/themepark/presentation/controller/ThemeparkControllerApiV1Test.java
themepark-service/src/test/java/com/business/themeparkservice/waiting/presentation/controller/WaitingControllerApiV1Test.java

- 대기열 기능 수행 시 userId를 토큰에서 받아오도록 수정
- 대기열 테스트코드 수정
**현재 테스트코드는 aop 권한체크 진행시 오류가 발생합니다. - 테스트코드 내에서 권한을 전달하는방법을 아직 찾지못했습니다.**
**권한체크를 주석처리한 뒤 수행하면 정상적으로 테스트 진행됩니다. 해당부분 이후에 수정하도록 하겠습니다.**

🔨 refactor[#187-themepark] 테마파크 대기열 코드 리팩토링

---

gateway-service/src/main/java/com/business/gatewayservice/infrastructure/config/SecurityConfig.java
order-service/src/main/java/com/sparta/orderservice/payment/application/service/PaymentService.java

🔨 refactor [Refactor/#201 order refactory]

---

gateway-service/src/main/java/com/business/gatewayservice/infrastructure/config/SecurityConfig.java

✏️ fix [/#201 order refactory] yml 파일 수정

---

themepark-service/src/main/java/com/business/themeparkservice/waiting/application/exception/WaitingExceptionCode.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/application/service/WaitingServiceImplApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/domain/repository/WaitingRepository.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/presentation/controller/WaitingControllerApiV1.java
themepark-service/src/test/java/com/business/themeparkservice/httpclient/hashtags.http
themepark-service/src/test/java/com/business/themeparkservice/httpclient/waitings.http

- 삭제 권한 해제
- repository 수정
- 테스트 코드수정
- 에러리턴 코드 추가
- 대기열 생성시 이미 '대기중' 인 값이 존재하는경우 대기가 생성되지않도록 구현

🔨 refactor[#210-waiting] 대기열 코드 리팩토링

---

product-service/src/main/java/com/business/productservice/presentation/controller/ProductControllerApiV1.java
product-service/src/test/java/com/business/productservice/product/presentation/controller/ProductControllerApiV1Test.java
product-service/src/test/resources/httpclient/product.http

✨ feat [#196-product-auth] 상품 서비스 권한 추가

---

slack-service/src/main/java/com/business/slackservice/SlackServiceApplication.java
slack-service/src/main/java/com/business/slackservice/application/dto/request/slackEventType/ReqSlackEventTypePostDTOApiV1.java
slack-service/src/main/java/com/business/slackservice/application/dto/request/slackEventType/ReqSlackEventTypePutDTOApiV1.java
slack-service/src/main/java/com/business/slackservice/application/dto/response/slackEventType/ResSlackEventTypeGetByIdDTOV1.java
slack-service/src/main/java/com/business/slackservice/application/dto/response/slackEventType/ResSlackEventTypeGetDTOV1.java
slack-service/src/main/java/com/business/slackservice/application/dto/response/slackEventType/ResSlackEventTypePostDTOApiV1.java
slack-service/src/main/java/com/business/slackservice/application/exception/SlackExceptionCode.java
slack-service/src/main/java/com/business/slackservice/application/service/SlackEventTypeServiceApiV1.java
slack-service/src/main/java/com/business/slackservice/application/service/SlackEventTypeServiceImplApiV1.java
slack-service/src/main/java/com/business/slackservice/domain/slack/entity/SlackEventTypeEntity.java
slack-service/src/main/java/com/business/slackservice/domain/slack/repository/SlackEventTypeRepository.java
slack-service/src/main/java/com/business/slackservice/infrastructure/persistence/SlackEventTypeJpaRepository.java
slack-service/src/main/java/com/business/slackservice/presentation/controller/SlackEventTypeControllerV1.java

- 슬랙 이벤트 타입 CRUD 구현
Create
Read
Update
Delete

✨ feat [#218-slack-event-type] 슬랙 이벤트 타입 CRUD 구현

---

slack-service/src/main/java/com/business/slackservice/application/dto/request/slackEventType/ReqSlackEventTypePostDTOApiV1.java
slack-service/src/main/java/com/business/slackservice/application/dto/request/slackEventType/ReqSlackEventTypePutDTOApiV1.java
slack-service/src/main/java/com/business/slackservice/application/dto/response/slackEventType/ResSlackEventTypeGetByIdDTOV1.java
slack-service/src/main/java/com/business/slackservice/application/dto/response/slackEventType/ResSlackEventTypeGetDTOV1.java
slack-service/src/main/java/com/business/slackservice/application/dto/response/slackEventType/ResSlackEventTypePostDTOApiV1.java
slack-service/src/main/java/com/business/slackservice/application/service/SlackEventTypeService.java
slack-service/src/main/java/com/business/slackservice/application/service/SlackEventTypeServiceImplApiV1.java
slack-service/src/main/java/com/business/slackservice/domain/slack/entity/SlackEntity.java
slack-service/src/main/java/com/business/slackservice/domain/slack/repository/SlackTemplateRepository.java
slack-service/src/main/java/com/business/slackservice/domain/slackEventType/entity/SlackEventTypeEntity.java
slack-service/src/main/java/com/business/slackservice/domain/slackEventType/repository/SlackEventTypeRepository.java
slack-service/src/main/java/com/business/slackservice/domain/slackTemplate/entity/SlackTemplateEntity.java
slack-service/src/main/java/com/business/slackservice/domain/slackTemplate/repository/SlackTemplateRepository.java
slack-service/src/main/java/com/business/slackservice/infrastructure/persistence/SlackEventTypeJpaRepository.java
slack-service/src/main/java/com/business/slackservice/infrastructure/persistence/SlackTemplateJpaRepository.java
slack-service/src/main/java/com/business/slackservice/presentation/controller/SlackEventTypeControllerV1.java

🔨 refactor [#220-slack] 패키지 구조 변경 및 파일 이동

---

order-service/build.gradle
order-service/src/main/java/com/sparta/orderservice/order/application/dto/reponse/ResProductGetByIdDTOApiV1.java
order-service/src/main/java/com/sparta/orderservice/order/application/exception/OrderExceptionCode.java
order-service/src/main/java/com/sparta/orderservice/order/infrastructure/feign/ProductOrderClient.java
order-service/src/main/java/com/sparta/orderservice/order/infrastructure/repository/JpaOrderRepository.java
order-service/src/main/java/com/sparta/orderservice/order/presentation/controller/OrderControllerApiV1.java
order-service/src/main/java/com/sparta/orderservice/payment/application/exception/PaymentExceptionCode.java
order-service/src/main/java/com/sparta/orderservice/payment/application/service/PaymentService.java
order-service/src/main/java/com/sparta/orderservice/payment/infrastructure/feign/ProductPaymentClient.java
order-service/src/main/java/com/sparta/orderservice/payment/infrastructure/repository/JpaPaymentRepository.java
order-service/src/main/java/com/sparta/orderservice/payment/presentation/dto/request/ReqPaymentPostDtoApiV1.java
order-service/src/main/resources/static/orders.html
order-service/src/main/resources/static/payments.html
order-service/src/main/resources/static/success.html
order-service/src/test/java/com/sparta/orderservice/presentation/controller/OrderControllerApiV1Test.java
product-service/src/main/java/com/business/productservice/application/exception/ProductExceptionCode.java
product-service/src/main/java/com/business/productservice/application/service/ProductServiceImplApiV1.java

feign product 를 위한 코드 구조 개선 
feign product 기능을 구현하였습니다.
주문생성시  EVENT 상품을 확인하고 EVENT 상품이라면 재고를 차감 진행 -> 결제도중 결제가 failure 됐다면 재고를 다시 복구시키는 
기능을 구현하였습니다.

✨ feat & 🔨 refacto [#201-order-refactory] product feign 기능 추가 및 구조 리펙토링

---

product-service/src/main/java/com/business/productservice/domain/product/entity/StockEntity.java

✏️ fix [#213-product] 재고차감/복구 조건문 추가

---

slack-service/src/test/java/com/business/slackservice/httpClient/slack.http

- slack CRD 테스트
- slackTemplate CRUD 테스트
- slackEventType CRUD 테스트

🎈 test [#229-slack] slack 관련 crud http test 생성

---

slack-service/src/main/java/com/business/slackservice/application/dto/request/slackEventType/ReqSlackEventTypePostDTOApiV1.java
slack-service/src/main/java/com/business/slackservice/application/dto/request/slackEventType/ReqSlackEventTypePutDTOApiV1.java
slack-service/src/main/java/com/business/slackservice/presentation/controller/SlackEventTypeControllerApiV1.java
slack-service/src/test/java/com/business/slackservice/slack/presentation/controller/SlackEventTypeControllerApiV1Test.java

- SlackEventType CRUD 테스트 코드 작성

🎈 test [#231 slack] SlackEventType Controller 테스트 코드 작성

---

gateway-service/src/main/java/com/business/gatewayservice/infrastructure/filter/CustomPreFilter.java
user-service/src/main/java/com/business/userservice/infrastructure/jwt/JwtAuthenticationFilter.java
user-service/src/main/java/com/business/userservice/infrastructure/jwt/JwtUtil.java
user-service/src/main/java/com/business/userservice/infrastructure/security/UserDetailsImpl.java
user-service/src/test/java/com/business/userservice/user/presentation/controller/AuthControllerApiV1Test.java

- jwt에 slack id 추가
- 헤더에 X-User-SlackId 추가

✨ feat [#233 user] jwt에 slackId 추가

---

slack-service/src/main/java/com/business/slackservice/application/dto/request/slack/ReqSlackPostDTOApiV1.java
slack-service/src/main/java/com/business/slackservice/application/service/SlackEventTypeService.java
slack-service/src/main/java/com/business/slackservice/application/service/SlackServiceImplApiV1.java
slack-service/src/main/java/com/business/slackservice/domain/slackEventType/repository/SlackEventTypeRepository.java
slack-service/src/test/java/com/business/slackservice/httpClient/slack.http

🔨 refactor [#235 slack] EventType Id 조회에서 Name 조회로 변경

---

user-service/build.gradle
user-service/src/main/java/com/business/userservice/presentation/controller/AuthControllerApiV1.java
user-service/src/main/java/com/business/userservice/presentation/controller/UserControllerApiV1.java

- common 버전 수정
- Auth, User Controller ResDTO Code String으로 변환

🔨 refactor [#242-user] ResDTO Code 자료형 변경

---

gateway-service/src/main/java/com/business/gatewayservice/infrastructure/config/SecurityConfig.java
slack-service/src/main/java/com/business/slackservice/presentation/controller/SlackControllerV1.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/infastructure/dto/request/ReqSlackPostDTOApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/infastructure/feign/SlackFeignClientApiV1.java

- type 입력  클래스 변경
- security config  cors 설정 포트번호 변경
- controller 제거

✨ feat [#223-waiting] 대기열 슬랙구현

---

slack-service/build.gradle
slack-service/src/main/java/com/business/slackservice/presentation/controller/SlackControllerApiV1.java
slack-service/src/main/java/com/business/slackservice/presentation/controller/SlackEventTypeControllerApiV1.java
slack-service/src/main/java/com/business/slackservice/presentation/controller/SlackTemplateControllerApiV1.java
slack-service/src/test/java/com/business/slackservice/httpClient/slack.http
slack-service/src/test/java/com/business/slackservice/slack/presentation/controller/SlackControllerApiV1Test.java

- ResDTO Code Integer -> String 변경
- 내부 전용 api에 /internal 경로 추가

🔨 refactor [#245 slack] ResDTO Code 수정 및 내부 전용 api 경로 수정

---

order-service/src/test/java/com/sparta/orderservice/httpclient/orders.http
order-service/src/test/java/com/sparta/orderservice/presentation/controller/OrderControllerApiV1Test.java

✨ feat  테스트용 http client 생성

---

slack-service/src/main/java/com/business/slackservice/application/service/RealSlackMessageSender.java
slack-service/src/main/java/com/business/slackservice/application/service/SlackMessageSender.java
slack-service/src/main/java/com/business/slackservice/application/service/SlackServiceImplApiV1.java
slack-service/src/main/java/com/business/slackservice/application/service/mock/MockSlackMessageSender.java
slack-service/src/main/resources/application-performance.yml
slack-service/src/main/resources/application.yml
slack-service/src/test/java/com/business/slackservice/httpClient/slack.http

- 성능 테스트용 yml 파일 생성
- 슬랙 메시지 보내는 기능을 interface로 분리

🎈 test [#249 slack] 성능 테스트용 yml 파일 생성

---

gateway-service/build.gradle
gateway-service/src/main/java/com/business/gatewayservice/application/exception/GatewayExceptionCode.java
gateway-service/src/main/java/com/business/gatewayservice/infrastructure/config/RedisConfig.java
gateway-service/src/main/java/com/business/gatewayservice/infrastructure/filter/CustomPreFilter.java
gateway-service/src/main/java/com/business/gatewayservice/infrastructure/jwt/JwtTokenProvider.java
gateway-service/src/main/java/com/business/gatewayservice/infrastructure/persistence/redis/BlacklistRepository.java
gateway-service/src/main/java/com/business/gatewayservice/infrastructure/persistence/redis/BlacklistRepositoryImpl.java

각 서비스 api에 요청을 보낼 때 해당 jwt가 blacklist 설정이 되어있는지 확인하는 기능을 구현했습니다.

✨ feat [#259 gateway] 블랙리스트 확인

---

gateway-service/src/main/resources/application.yml
slack-service/src/main/resources/application-dev.yml
user-service/src/main/resources/application-dev.yml

⚙ setting [#266-slack-user-gateway] Redis 설정

---

gateway-service/src/main/java/com/business/gatewayservice/infrastructure/config/RedisConfig.java
slack-service/src/main/java/com/business/slackservice/infrastructure/config/RedisConfig.java
user-service/src/main/java/com/business/userservice/infrastructure/config/RedisConfig.java

어플리케이션 실행 시 Unable to connect to Redis 오류가 발생했습니다.
Spring 쪽에서 인증 정보를 제공하지 않아서 발생한 문제였습니다.
RedisConnectionFactory 설정에 host, port, password 값을 주입했고 오류 없이 잘 실행됩니다.

🐛 bug [#270-gateway-user-slack] Unable to connect to Redis 문제 해결

---

slack-service/src/main/resources/application-performance.yml

⚙ setting [#276-slack] performance.yml에 redis 설정 추가

---

product-service/src/main/java/com/business/productservice/application/dto/v1/request/ReqProductPostDTOApiV1.java
product-service/src/main/java/com/business/productservice/application/dto/v1/request/ReqProductPutDTOApiV1.java
product-service/src/main/java/com/business/productservice/application/dto/v1/request/ReqStockDecreasePostDTOApiV1.java
product-service/src/main/java/com/business/productservice/application/dto/v1/request/ReqStockRestorePostDTOApiV1.java
product-service/src/main/java/com/business/productservice/application/dto/v1/response/ResProductGetByIdDTOApiV1.java
product-service/src/main/java/com/business/productservice/application/dto/v1/response/ResProductGetDTOApiV1.java
product-service/src/main/java/com/business/productservice/application/dto/v1/response/ResProductPostDTOApiV1.java
product-service/src/main/java/com/business/productservice/application/dto/v1/response/ResProductPutDTOApiV1.java
product-service/src/main/java/com/business/productservice/application/dto/v1/response/ResStockGetByIdDTOApiV1.java
product-service/src/main/java/com/business/productservice/application/dto/v2/request/ReqProductPostDTOApiV2.java
product-service/src/main/java/com/business/productservice/application/dto/v2/request/ReqProductPutDTOApiV2.java
product-service/src/main/java/com/business/productservice/application/dto/v2/request/ReqStockDecreasePostDTOApiV2.java
product-service/src/main/java/com/business/productservice/application/dto/v2/request/ReqStockRestorePostDTOApiV2.java
product-service/src/main/java/com/business/productservice/application/dto/v2/response/ResProductGetByIdDTOApiV2.java
product-service/src/main/java/com/business/productservice/application/dto/v2/response/ResProductGetDTOApiV2.java
product-service/src/main/java/com/business/productservice/application/dto/v2/response/ResProductPostDTOApiV2.java
product-service/src/main/java/com/business/productservice/application/dto/v2/response/ResProductPutDTOApiV2.java
product-service/src/main/java/com/business/productservice/application/dto/v2/response/ResStockGetByIdDTOApiV2.java
product-service/src/main/java/com/business/productservice/application/service/v1/ProductServiceApiV1.java
product-service/src/main/java/com/business/productservice/application/service/v1/ProductServiceImplApiV1.java
product-service/src/main/java/com/business/productservice/application/service/v2/ProductServiceApiV2.java
product-service/src/main/java/com/business/productservice/application/service/v2/ProductServiceImplApiV2.java
product-service/src/main/java/com/business/productservice/presentation/controller/v1/ProductControllerApiV1.java
product-service/src/main/java/com/business/productservice/presentation/controller/v2/ProductControllerApiV2.java
product-service/src/test/java/com/business/productservice/application/service/v1/ProductServiceImplApiV1Test.java
product-service/src/test/java/com/business/productservice/application/service/v2/ProductServiceImplApiV2Test.java
product-service/src/test/java/com/business/productservice/product/presentation/controller/ProductControllerApiV1Test.java
product-service/src/test/resources/httpclient/productV2.http

- 기존 페인클라이언트, db에 비관락 방식 적용한 v1에서 v2 분리하였습니다.
- v2: 재고 차감이 분산락으로 동시성 제어가 되고 있으며, 재고 조회를 레디스에 캐싱할 예정입니다. 
- 비관락
- Redisson 분산락
* 리팩토링 한 결과의 성능이 더 낮아서.. 이 부분 고민이 됩니다

🔨 refactor [#269-product] 상품 서비스 v2 분리

---

product-service/build.gradle
product-service/src/main/resources/application-dev.yml

⚙ setting [#281-product-monitoring] prometheus, Grafana 모니터링 설정

---

gateway-service/src/main/java/com/business/gatewayservice/infrastructure/filter/CustomPreFilter.java
gateway-service/src/main/resources/application.yml

🔨 refactor [#296-gateway] 라우팅 경로 수정

---

user-service/src/main/java/com/business/userservice/application/service/AuthServiceImplApiV1.java
user-service/src/main/java/com/business/userservice/domain/user/repository/BlacklistRepository.java
user-service/src/main/java/com/business/userservice/domain/user/repository/BlacklistRepositoryImpl.java

블랙리스트 조회 메서드 반환 타입 수정
String -> Timestamp

✏️ fix [#299-user] 블랙리스트 조회 메서드 반환 타입 수정

---

docker-compose.yml
themepark-service/build.gradle
themepark-service/src/main/resources/application-dev.yml

- prometheus,grafana 설정
- docker-compose 추가수정

⚙ setting[#292-themepark] 테마파크 모니터링 설정

---

slack-service/src/main/resources/application-dev.yml

✏️ fix [#304-slack] kafka 포트 번호 수정

---

gateway-service/src/main/java/com/business/gatewayservice/infrastructure/filter/CustomPreFilter.java
themepark-service/src/main/java/com/business/themeparkservice/themepark/application/dto/request/ReqThemeparkPostDTOApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/themepark/application/dto/request/ReqThemeparkPutDTOApiV1.java
themepark-service/src/test/java/com/business/themeparkservice/httpclient/themeparks.http

- requestdto hashtag name 컬럼 제거
- 토큰이 없어도 query문을 사용한 검색기능이 진행되도록 엔드포인트 수정

✏️ fix[#303-themepark] 테마파크 코드 수정

---

themepark-service/src/main/java/com/business/themeparkservice/waiting/application/service/v1/WaitingServiceImplApiV1.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/application/service/v2/WaitingServiceImplApiV2.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/application/service/v3/WaitingServiceImplApiV3.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/domain/entity/WaitingEntity.java
themepark-service/src/main/java/com/business/themeparkservice/waiting/domain/vo/WaitingStatus.java
themepark-service/src/test/java/com/business/themeparkservice/themepark/presentation/controller/ThemeparkControllerApiV1Test.java
themepark-service/src/test/java/com/business/themeparkservice/waiting/presentation/controller/WaitingControllerApiV3Test.java

- 대기타입 오타수정
**CANCELLED -> CANCELED**

✏️ fix [#303-themepark] 테마파크 코드 수정

---

themepark-service/build.gradle
themepark-service/src/main/resources/application-dev.yml
themepark-service/src/test/java/com/business/themeparkservice/hashtag/presentation/controller/HashtagControllerApiV1Test.java
themepark-service/src/test/java/com/business/themeparkservice/themepark/presentation/controller/ThemeparkControllerApiV1Test.java
themepark-service/src/test/java/com/business/themeparkservice/waiting/presentation/controller/WaitingControllerApiV3Test.java

⚙ setting[#309-themepark] 테마파크 zipkin 설정

---

user-service/src/test/java/com/business/userservice/user/presentation/controller/AuthControllerApiV1Test.java
user-service/src/test/java/com/business/userservice/user/presentation/controller/UserControllerApiV1Test.java

- 헤더에 권한 추가
- refresh 테스트 코드 수정
- 매니저 회원가입 테스트 코드 작성

🎈 test [#313 user] 테스트 코드 수정

---

slack-service/src/test/java/com/business/slackservice/slack/presentation/controller/SlackControllerApiV3Test.java
slack-service/src/test/java/com/business/slackservice/slack/presentation/controller/SlackEventTypeControllerApiV3Test.java
slack-service/src/test/java/com/business/slackservice/slack/presentation/controller/SlackTemplateControllerApiV3Test.java

🎈 test  [#315-slack] v3으로 테스트 코드 수정

---

order-service/src/main/java/com/sparta/orderservice/order/application/exception/OrderExceptionCode.java
order-service/src/main/java/com/sparta/orderservice/order/application/helper/OrderTransactionHelper.java
order-service/src/main/java/com/sparta/orderservice/order/application/service/v3/OrderServiceV3.java
order-service/src/main/java/com/sparta/orderservice/order/application/usecase/v3/OrderUseCaseV3.java
order-service/src/main/java/com/sparta/orderservice/order/domain/repository/OrderRepository.java
order-service/src/main/java/com/sparta/orderservice/order/infrastructure/repository/JpaOrderRepository.java
order-service/src/main/java/com/sparta/orderservice/order/presentation/dto/v1/request/ReqOrderPutDtoApiV1.java
order-service/src/main/resources/application-test.yml
order-service/src/test/java/com/sparta/orderservice/presentation/controller/OrderControllerApiV3Test.java
order-service/src/test/java/com/sparta/orderservice/presentation/controller/PaymentControllerApiV3Test.java

✨ feat [#320-order-transaction] 보상트랜잭션 구현

---

order-service/src/main/java/com/sparta/orderservice/order/application/helper/OrderTransactionHelper.java
order-service/src/main/java/com/sparta/orderservice/order/application/service/v3/OrderServiceV3.java
order-service/src/main/java/com/sparta/orderservice/order/infrastructure/kafka/config/KafkaConsumeConfig.java
order-service/src/main/java/com/sparta/orderservice/order/infrastructure/kafka/config/KafkaProduceConfig.java
order-service/src/main/java/com/sparta/orderservice/order/infrastructure/kafka/consumer/ProductConsumer.java
order-service/src/main/java/com/sparta/orderservice/order/infrastructure/kafka/dto/req/ReqProductKafkaDto.java
order-service/src/main/java/com/sparta/orderservice/order/infrastructure/kafka/dto/res/ResProductKafkaDto.java
order-service/src/main/java/com/sparta/orderservice/order/infrastructure/kafka/service/KafkaService.java

✨ feat [#323-order-kafka] product 재고 차감 요청시 메세지 받기

---

order-service/src/main/java/com/sparta/orderservice/order/application/helper/OrderTransactionHelper.java
order-service/src/main/java/com/sparta/orderservice/order/infrastructure/kafka/config/KafkaConsumeConfig.java
order-service/src/main/java/com/sparta/orderservice/order/infrastructure/kafka/config/KafkaProduceConfig.java
order-service/src/main/java/com/sparta/orderservice/order/infrastructure/kafka/dto/res/ResProductKafkaDto.java
order-service/src/main/java/com/sparta/orderservice/order/infrastructure/kafka/service/KafkaService.java
order-service/src/test/java/com/sparta/orderservice/httpclient/orders.http
product-service/src/main/java/com/business/productservice/infrastructure/config/KafkaConfig.java
themepark-service/src/test/java/com/business/themeparkservice/httpclient/waitings.http

✏️ fix   [#323 order kafka] order,product kafka 기능 fix

---

order-service/src/main/java/com/sparta/orderservice/order/application/helper/OrderTransactionHelper.java
order-service/src/main/java/com/sparta/orderservice/order/application/service/v3/OrderServiceV3.java
order-service/src/main/java/com/sparta/orderservice/order/domain/entity/OrderEntity.java
order-service/src/main/java/com/sparta/orderservice/order/infrastructure/kafka/consumer/ProductConsumer.java
order-service/src/main/java/com/sparta/orderservice/payment/domain/vo/PaymentStatus.java

✨ feat  [#323-order-kafka] 재고 차감 요청에 따른 처리기능 구현

---

order-service/src/main/resources/application-prod.yml
order-service/src/main/resources/application.yml
product-service/src/main/resources/application-prod.yml
product-service/src/main/resources/application.yml
slack-service/src/main/resources/application-prod.yml
slack-service/src/main/resources/application.yml
themepark-service/src/main/resources/application-prod.yml
themepark-service/src/main/resources/application.yml
user-service/src/main/resources/application-prod.yml
user-service/src/main/resources/application.yml

application-prod.yml 생성

---

product-service/src/main/java/com/business/productservice/infrastructure/config/KafkaConfig.java
slack-service/src/main/java/com/business/slackservice/infrastructure/config/ConsumerApplicationKafkaConfig.java

localhost > ip 주소 수정

---

order-service/src/main/java/com/sparta/orderservice/order/infrastructure/kafka/config/KafkaConsumeConfig.java
order-service/src/main/java/com/sparta/orderservice/order/infrastructure/kafka/config/KafkaProduceConfig.java

✏️ fix ec2 주소로 변경

---

themepark-service/src/main/java/com/business/themeparkservice/waiting/config/KafkaConfig.java

- 배포적용을위한 kafkaconfig host주소 변경

🔨 refactor kafka host주소 변경

---

gateway-service/src/main/resources/application-prod.yml
slack-service/src/main/java/com/business/slackservice/application/service/RealSlackMessageSender.java

timeoutDuration 6s -> 60s
@Profile dev -> prod

🐛 bug [#339 gateway slack] timeoutDuration, @Profile 설정 변경

---

docker-compose.yml
eureka-server/Dockerfile
eureka-server/src/main/resources/application.yml

Docker 환경에서 Eureka 등록 주소 수정 및 dockerfile 생성
- localhost → eureka-server

✏️ fix [#341-eureka-docker] Docker 환경에서 Eureka 등록 주소 수정 및 dockerfile 생성

---

README.md

✏️ fix Update README.md
