numberOnethemepark/themepark

themepark-service/src/main/java/com/business/themeparkservice/themepark/application/dto/response/ResThemeparkGetByIdDTOApiV1.java, themepark-service/src/main/java/com/business/themeparkservice/themepark/common/dto/ResDTO.java, themepark-service/src/main/java/com/business/themeparkservice/themepark/presentation/controller/ThemeparkControllerApiV1.java, themepark-service/src/test/java/com/business/themeparkservice/httpclient/themeparks.http
- 공통응답 Dto 생성 및 Controller에 추가
- Read ResponseDto 구현
- Test code 추가
- 입력코드
--------
- 결과
=> ✨ feat [#21-themepark-read] 테마파크 Read 기능 구현

gateway-service/src/main/resources/application.yml, order-service/build.gradle, order-service/src/main/java/com/sparta/orderservice/application/dto/request/ReqOrderPutDtoApiV1.java, order-service/src/main/java/com/sparta/orderservice/application/dto/request/ReqOrdersPostDtoApiV1.java, order-service/src/main/java/com/sparta/orderservice/presentation/controller/OrderControllerApiV1.java, themepark-service/src/main/java/com/business/themeparkservice/hashtag/application/dto/request/ReqHashtagPostDTOApiV1.java, themepark-service/src/main/java/com/business/themeparkservice/hashtag/application/dto/response/ResHashtagPostDTOApiV1.java, themepark-service/src/main/java/com/business/themeparkservice/hashtag/common/dto/ResDTO.java, themepark-service/src/main/java/com/business/themeparkservice/hashtag/presentation/controller/HashtagControllerApiV1.java, themepark-service/src/test/java/com/business/themeparkservice/httpclient/hashtags.http, user-service/src/main/java/com/business/userservice/application/dto/request/ReqUserPutDTOApiV1.java, user-service/src/main/java/com/business/userservice/presentation/controller/UserControllerApiV1.java
- 해시태그 controller 작성
- create api 코드작성
- create api 관련 request,respone dto 작성
- create api 테스트 코드 작성
- gateway hashtag 엔드포인트 추가
-작성코드&결과
=> ✨ feat[#22-hashtag-create] 해시태그 Create 기능 구현

themepark-service/build.gradle, themepark-service/src/main/java/com/business/themeparkservice/hashtag/application/dto/response/ResHashtagGetDTOApiV1.java, themepark-service/src/main/java/com/business/themeparkservice/hashtag/domain/entity/HashtagEntity.java, themepark-service/src/main/java/com/business/themeparkservice/hashtag/presentation/controller/HashtagControllerApiV1.java, themepark-service/src/main/java/com/business/themeparkservice/themepark/application/dto/response/ResThemeparkGetDTOApiV1.java, themepark-service/src/main/java/com/business/themeparkservice/themepark/domain/entity/ThemeparkEntity.java, themepark-service/src/main/java/com/business/themeparkservice/themepark/presentation/controller/ThemeparkControllerApiV1.java, themepark-service/src/test/java/com/business/themeparkservice/httpclient/hashtags.http, themepark-service/src/test/java/com/business/themeparkservice/httpclient/themeparks.http
- search api 구현
- search api 관련 resposneDto 생성
- HashtagEntity 생성
- 테스트 코드 작성
-엔드포인트
---
-결과
=> ✨ feat [#22-hashtag-search] 테마파크해시태그 Search 기능 구현

themepark-service/build.gradle, themepark-service/src/test/java/com/business/themeparkservice/hashtag/presentation/controller/HashtagControllerApiV1Test.java, themepark-service/src/test/java/com/business/themeparkservice/themepark/presentation/controller/ThemeparkControllerApiV1Test.java, themepark-service/src/test/java/com/business/themeparkservice/waiting/presentation/controller/WaitingControllerApiV1Test.java
- build.gradle 에 swagger 의존성 추가
- 테마파크 테스트코드 swagger 문서화 연결
- 해시태그 테스트코드 swagger 문서화 연결
- 대기 테스트코드 swagger 문서화 연결
*게이트웨이에 작성해야하는 swagger 경로는 병합오류를 고려하여 제외하고 올렸습니다!*
=> 📄 docs[#89-themepark] 테마파크 swagger 자동 문서화기능 추가

themepark-service/src/main/java/com/business/themeparkservice/hashtag/application/service/HashtagServiceApiV1.java, themepark-service/src/main/java/com/business/themeparkservice/hashtag/application/service/HashtagServiceImplApiV1.java, themepark-service/src/main/java/com/business/themeparkservice/hashtag/domain/entity/HashtagEntity.java, themepark-service/src/main/java/com/business/themeparkservice/hashtag/presentation/controller/HashtagControllerApiV1.java, themepark-service/src/test/java/com/business/themeparkservice/httpclient/hashtags.http
- service 로직추가
- soft delete 이후 삭제된 해시태그 조회 불가능하도록 구현
- 테스트코드 수정
- @SQLRestriction("deleted_at IS NULL") 
- 해당 어노테이션을 사용하여 삭제정보가 존재할 시 검색되지않도록 조건을 추가할수 있습니다.
=> ✨ feat [#128-hashtag-delete] 해시태그 삭제 기능 구현

product-service/build.gradle, product-service/src/main/java/com/business/productservice/application/dto/response/ResProductGetDTOApiV1.java, product-service/src/main/java/com/business/productservice/application/service/ProductServiceApiV1.java, product-service/src/main/java/com/business/productservice/application/service/ProductServiceImplApiV1.java, product-service/src/main/java/com/business/productservice/domain/product/repository/ProductRepository.java, product-service/src/main/java/com/business/productservice/infrastructure/persistence/product/ProductJpaRepository.java, product-service/src/main/java/com/business/productservice/presentation/controller/ProductControllerApiV1.java, product-service/src/test/resources/httpclient/product.http
- 상품 검색 api에 Querydsl 기반 조건 검색 및 페이징 기능 구현
- PageableDefault를 통한 페이징 처리
- JpaRepository에 Querydsl의 Predicate를 받아 동적 쿼리 실행할 수 있도록 QuerydslPredicateExecutor 구현
- 공통레포 0.0.7버전으로 변경
- 응답 dto 객체 > dto 변환 구현
=> ✨ feat [#142-product-search] 상품 다중 검색 기능 구현

themepark-service/src/main/java/com/business/themeparkservice/themepark/application/service/ThemeparkServiceApiV1.java, themepark-service/src/main/java/com/business/themeparkservice/themepark/application/service/ThemeparkServiceImplApiV1.java, themepark-service/src/main/java/com/business/themeparkservice/themepark/domain/entity/ThemeparkEntity.java, themepark-service/src/main/java/com/business/themeparkservice/themepark/domain/repository/ThemeparkHashtagRepository.java, themepark-service/src/main/java/com/business/themeparkservice/themepark/presentation/controller/ThemeparkControllerApiV1.java, themepark-service/src/test/java/com/business/themeparkservice/httpclient/themeparks.http
- service 로직 연결
- 테마파크 삭제 시 중간테이블 정보도 삭제되도록 구현
- 테스트코드 수정
=> ✨ feat [#147-themepark-delete] 테마파크 삭제 기능 구현

product-service/src/main/java/com/business/productservice/application/exception/ProductExceptionCode.java, product-service/src/main/java/com/business/productservice/application/service/ProductServiceApiV1.java, product-service/src/main/java/com/business/productservice/application/service/ProductServiceImplApiV1.java, product-service/src/main/java/com/business/productservice/domain/product/entity/StockEntity.java, product-service/src/main/java/com/business/productservice/domain/product/repository/StockRepository.java, product-service/src/main/java/com/business/productservice/domain/product/repository/StockRepositoryImpl.java, product-service/src/main/java/com/business/productservice/presentation/controller/ProductControllerApiV1.java, product-service/src/test/resources/httpclient/product.http
- 해당 id(상품id와 동일한 값)의 재고 값을 1씩 감소 시키는 비즈니스 로직 구현 - 1인 1구매 가능 (순착순 티켓팅)
- 재고가 0보다 작거나 같을 경우 예외처리 (매진 메세지)
-  재고가 1개일 때 동시에 여러 요청이 들어오는 경우 중복 차감되는 문제 방지하기 위해 비관적 락 적용
- StockRepository의 구현체인 StockRepositoryImpl 파일 생성
- StockRepositoryImpl에서 EntityManager로 직접 락 처리
*부하 테스트는 추후 JMeter로 진행할 예정입니다.
=> ✨ feat [#144-product-stock-decrease] 상품-재고 차감 기능 구현

themepark-service/src/main/java/com/business/themeparkservice/ThemeparkServiceApplication.java, themepark-service/src/main/java/com/business/themeparkservice/hashtag/application/exception/HashtagExceptionCode.java, themepark-service/src/main/java/com/business/themeparkservice/hashtag/application/service/HashtagServiceImplApiV1.java, themepark-service/src/main/java/com/business/themeparkservice/themepark/application/exception/ThemeparkExceptionCode.java, themepark-service/src/main/java/com/business/themeparkservice/themepark/application/service/ThemeparkServiceImplApiV1.java, themepark-service/src/main/java/com/business/themeparkservice/waiting/application/exception/WaitingExceptionCode.java, themepark-service/src/main/java/com/business/themeparkservice/waiting/application/service/WaitingServiceImplApiV1.java
- 테마파크,해시태그,대기열 커스텀 에러리턴코드 작성
- 테마파크,해시태그,대기열 커스텀 에러리턴코드 적용
- 응답 리턴코드 적용을위한 scanbasePackages 경로 추가
- 
=> 🔨 refactor[#165-themepark-error] 테마파크 에러리턴코드 리팩토링

gateway-service/src/main/java/com/business/gatewayservice/infrastructure/filter/CustomPreFilter.java
=> 🔨 refactor [#214-gateway-jwt] jwt 필터에 HTTP 메소드별 경로 제외 설정 추가

themepark-service/build.gradle, themepark-service/src/main/java/com/business/themeparkservice/ThemeparkServiceApplication.java, themepark-service/src/main/java/com/business/themeparkservice/waiting/application/service/WaitingServiceImplApiV1.java, themepark-service/src/main/java/com/business/themeparkservice/waiting/domain/repository/WaitingRepository.java
- 비관적 락 적용을 위한 repository,service 수정
-  springboot 기본 aop 어노테이션 추가
- 오류 발생시 재시도할수있도록 enableretry 어노테이션 추가
- for share 를 사용하여 접근성 완화
- 오류 클래스 작성을위한 postgresql 의존성 추가
**현재 동시성 테스트 진행을 위해 회원대기 중복체크 부분을 주석처리해두었습니다!**
---
**락이 걸린것을 확인하기위해 sql 로그를 보던 중 for update 가 아닌 그보다 더 낮은 수준의 락인 for no key update 발생**
-> 해당 이슈를 수정하기위해 native 쿼리문으로 작성진행하였습니다.
-> for share 로 변경하여 동시성 개선
---
**락은 정상적으로 걸렸으나, 다수의 트랜잭션이 조회하는 문제는 해결이 되지않아 값이 중복저장되는 문제발생 **
-> 트랜잭션의 격리수준이 낮아 발생한 문제로  `@Transactional(isolation = Isolation.SERIALIZABLE)` 을 사용
-> 직렬화 에러가 발생하여 이를 해결하기위해 `@Retryable` 을 추가하였습니다.
-> @Retryable 어노테이션이 붙은 빈(Bean)에 대한 프록시 객체를 생성하기위해 springboot 기본 aop를 추가하였습니다.
격리수준을 SERIALIZABLE 로 올리면 하나의 트랜잭션 수행중 다른트랜잭션이 읽는것을 방지할 수있습니다.
하지만 가장 강력한 격리수준이어서 데이터의 일관성을 엄격하게 보장해야 하는 특정 트랜잭션에 …
=> 🔨 refactor[#251-waiting-lock] 대기열 동시성 리팩토링

slack-service/build.gradle, slack-service/src/main/java/com/business/slackservice/application/service/SlackServiceImplApiV1.java, slack-service/src/main/java/com/business/slackservice/infrastructure/config/RedisConfig.java, slack-service/src/main/java/com/business/slackservice/infrastructure/persistence/SlackRedisRepository.java, slack-service/src/main/java/com/business/slackservice/infrastructure/persistence/SlackRedisRepositoryImpl.java
- 자주 조회되는 슬랙 이벤트 타입과 템플릿을 Redis에 저장했습니다.
- Redis에 저장되어있지 않은 경우 RDB에서 조회해서 Redis에 저장됩니다.
[Key] slack:event:이벤트타입이름 [Value] 이벤트타입ID
[Key] slack:template:이벤트타입이름 [Value] 템플릿 양식
JMeter로 성능 테스트를 진행한 결과 Redis 적용 전에는 평균 처리량이 416 req/sec였으나, 적용 후에는 평균 897 req/sec로 약 두 배 향상되었습니다.
=> ✨ feat [#261 slack] Slack EventType, Template Redis에 저장

docker-compose.yml, themepark-service/build.gradle, themepark-service/src/main/java/com/business/themeparkservice/ThemeparkServiceApplication.java, themepark-service/src/main/java/com/business/themeparkservice/waiting/application/dto/request/ReqWaitingPostDTOApiV1.java, themepark-service/src/main/java/com/business/themeparkservice/waiting/application/exception/WaitingExceptionCode.java, themepark-service/src/main/java/com/business/themeparkservice/waiting/application/service/WaitingServiceImplApiV1.java, themepark-service/src/main/java/com/business/themeparkservice/waiting/domain/entity/WaitingRedisEntity.java, themepark-service/src/main/java/com/business/themeparkservice/waiting/domain/repository/WaitingRedisRepository.java, themepark-service/src/main/java/com/business/themeparkservice/waiting/infastructure/feign/SlackFeignClientApiV1.java, themepark-service/src/main/java/com/business/themeparkservice/waiting/infastructure/feign/dto/request/ReqSlackPostDTOApiV1.java, themepark-service/src/main/java/com/business/themeparkservice/waiting/infastructure/feign/service/SlackFeignClientServiceApiV1.java, themepark-service/src/main/java/com/business/themeparkservice/waiting/infastructure/feign/vo/TargetType.java, themepark-service/src/main/java/com/business/themeparkservice/waiting/infastructure/persistence/waiting/WaitingJpaRepository.java, themepark-service/src/main/java/com/business/themeparkservice/waiting/infastructure/redis/WaitingCrudRedisRepository.java, themepark-service/src/main/java/com/business/themeparkservice/waiting/presentation/controller/WaitingControllerApiV1.java, themepark-service/src/main/resources/application-dev.yml
- redis 실행을 위한 docker-compose.yml 설정
- 서비스와의 연동을 위한 application-dev.yml 설정
- 분산락 적용을위한 redisson 의존성 설정
- redisRepository 와 일반 데이터베이스 repository 분리
- repositroy 분리로인한 빈 추가 오류가 발생하여 패키지 경로를 직접 작성하여 어노테이션 작성
- redis 캐싱 저장용 엔티티 작성
- 기존 비관적 락을 적용했던 대기열 생성 api를 redisson 분산 락과 합쳐서 활용
- 커스텀 에러코드 작성
**redis-> docker 로 적용하여 진행 중 게이트웨이에서 redis정보를 찾을수없다는 에러가 발생하여 
yml에 redis 정보를 추가하여 진행했었습니다. 현재 롤백한뒤 코드를 올린상황이며, 동일한 오류가 발생하는경우 
gateway에 redis 정보를 입력 하여 진행해야할것 같습니다**
[waiting:themepark:{themeparkId} 형식의 키값]
---
=> ✨ feat [#255-waiting-lock] 대기열 redis 분산락 캐싱 적용

user-service/src/main/java/com/business/userservice/infrastructure/jwt/JwtUtil.java
token 생성 시 기대했던 만료 시간과 일치하지 않는 문제가 발생했습니다.
System.currentTimeMillis()는 밀리초 단위인데 TokenExpiration에서 받은 값은 초 단위라서 그랬던 거였고
iat도 밀리초 기반이기 때문에 만료시간 계산할 때 초에서 밀리초로 변환하기 위해 * 1000을 추가했습니다.
Access Token
만료일: 1일
Refresh Token
만료일: 12일
=> ✏️ fix [#274-user] 토큰 만료 시간 계산 시 초에서 밀리초 단위 변환 누락 수정

docker-compose.yml, eureka-server/build.gradle, eureka-server/src/main/resources/application.yml, gateway-service/build.gradle, gateway-service/src/main/resources/application.yml, prometheus.yml, slack-service/build.gradle, slack-service/src/main/resources/application-dev.yml, slack-service/src/main/resources/application-performance.yml, user-service/build.gradle, user-service/src/main/resources/application-dev.yml
아래를 따라서 설정해주세요!
각 서비스에 의존성을 추가해주세요
```
// actuator
implementation 'org.springframework.boot:spring-boot-starter-actuator'
// prometheus
runtimeOnly 'io.micrometer:micrometer-registry-prometheus'
```
yml 파일에 아래를 추가해서 메트릭 수집하도록 합니다
```
management:
endpoints:
web:
exposure:
include: 'prometheus'
```
설정 후에
localhost:서비스포트번호/actuator
localhost:서비스포트번호/actuator/prometheus
엔드포인트를 검색해보시고 다음과 같은 response가 나오는지 확인해주세요
docker-compose에 prometheus랑 grafana 설정했습니다! 도커 다시 업 해주세요!
localhost:9090으로 들어가면 prometheus 연결됩니다!
localhost:9090/targets로 들어가면 각 서비스가 설정된 것을 확인할 수 있습니다!
status가 up이면 잘된겁니다!
localhost:3000으로 접속하고 로그인을 합니다
id: admin
pw: admin
각 서비스 대시보드를 볼 수 있습니다.
각 서비스 CPU 50% 이상 사용 시 슬랙 알람이 오게 설정했습니다.
확인해보시고 안되면 말씀해주세요
=> ⚙ setting [#279 common] Prometheus와 Grafana를 이용한 모니터링

gateway-service/src/main/java/com/business/gatewayservice/infrastructure/filter/CustomPreFilter.java, gateway-service/src/main/resources/application.yml, product-service/src/main/java/com/business/productservice/application/service/v2/ProductServiceImplApiV2.java, product-service/src/main/java/com/business/productservice/config/RedissonConfig.java, product-service/src/main/java/com/business/productservice/infrastructure/dto/ReqToSlackPostDTOApiV1.java, product-service/src/test/java/com/business/productservice/application/service/v2/ProductServiceImplApiV2Test.java
- 재고 차감 시 RedisTemplate을 이용해 재고 수량 캐싱
- RedisConfig에 RedisTemplate<String, Object> 설정 추가
- key는 String 직렬화, value는 JSON 직렬화
- 향후 주문 서비스에서 빠른 재고 확인을 위한 캐싱 도입
**v2를 분리하면서 gateway와 yml에 상품 서비스 path를 추가했습니다.
=> ✨ feat [#273-stock-cache] 재고 차감 시 재고 정보에 대한 캐싱 구현

gateway-service/build.gradle, gateway-service/src/main/resources/application.yml
localhost:8080/actuator/circuitbreakers 요청을 하면 등록된 서킷브레이커를 확인할 수 있습니다.
처음에는 CLOSED 상태입니다.
오류를 많이 발생해보겠습니다.
user service를 실행시키지 않은 상태에서 login 요청을 마구 보냈습니다
로그를 보면 어느 순간부터는 No servers available for service: user-service 경고가 발생하지 않습니다.
총 9건을 요청했는데 초반 5건이 실패되었고 그 후 요청된 4건이 차단됐습니다. 현재 서킷 상태는 OPEN으로 변경되었습니다.
일정 시간이 지나면 HALF_OPEN 상태로 변경됩니다.
이 상태에서는 요청을 몇 개 보내서 진짜 서버가 정상인지 확인해보는 상태입니다.
요청들이 성공하면 CLOSED 상태로 복귀하고 실패한다면 다시 OPEN으로 가서 차단됩니다.
Grafana 대시보드에서도 확인할 수 있습니다!
=> ⚙ setting [#285-gateway] Resilience4J 설정

product-service/src/main/java/com/business/productservice/application/exception/ProductExceptionCode.java, product-service/src/main/java/com/business/productservice/application/service/v3/ProductServiceImplApiV3.java, product-service/src/main/java/com/business/productservice/domain/product/entity/StockEntity.java
- 분산락 적용 및 재고 복구된 value를 레디스에 캐싱
- 무제한 복구 불가능하도록 엔티티 내부에서 처리
- 해당 요청이 온다면 로그를 남겨 확인
- 레디스 ttl 설정 : 5분 (실시간 정확한 재고 확인이 핵심이기 때문에 TTL을 너무 길게 주면 안 되고, 추천 TTL은 '3~5분' 정도가 가장 안전하면서 Redis 자원도 절약할 수 있다고 합니다)
=> ✨ feat [#310-product-restore-redis] 상품 재고 복구 레디스 분산락 적용 및 무제한 복구 처리 불가하도록 예외로직 추가

product-service/build.gradle, product-service/src/main/java/com/business/productservice/infrastructure/config/KafkaConfig.java, product-service/src/main/java/com/business/productservice/infrastructure/kafka/ProductKafkaConsumer.java, product-service/src/main/java/com/business/productservice/infrastructure/kafka/TestKafkaProducer.java, product-service/src/main/java/com/business/productservice/presentation/controller/v3/ProductControllerApiV3.java, product-service/src/main/resources/application-dev.yml, product-service/src/test/java/com/business/productservice/product/presentation/controller/v1/ProductControllerApiV1Test.java, product-service/src/test/java/com/business/productservice/product/presentation/controller/v3/ProductControllerApiV3Test.java, product-service/src/test/resources/httpclient/productV3.http
- DeadLetterPublishingRecoverer로 DLQ 설정
- FixedBackOff을 이용한 재시도 로직 적용 (1초 간격, 최대 3회)
- MANUAL_IMMEDIATE Ack 모드 설정
- 수동 Ack 모드 적용 (acknowledge 호출로 명시적 커밋 처리)
- DLQ 테스트를 위한 강제 예외 발생 코드 주석 처리
- 예외 발생 시 ack 생략 → Spring Kafka가 재시도 및 DLQ 이동 처리 가능
- Kafka Consumer 수동 ACK 설정
- 메시지 처리 실패 시 재시도 + DLQ 분기 처리
- 기존 메시지 처리 실패 시 유실 우려 존재
- 장애 대응을 위한 메시지 격리 및 추적이 어려움
- 운영 중 오류 메시지 식별 및 재처리 필요
- 메시지 유실 방지
- 장애 발생 시 DLQ를 통해 신속한 파악 및 재처리 가능
- Kafka 기반 시스템의 안정성 및 가시성 향상
=> ✨ feat [#318-product-kafka] 카프카 실패  시 DLQ 처리 로직 추가 및 수동 Ack 설정 / zipkin 의존성 추가

gateway-service/src/main/resources/application-prod.yml
TimeLimiter 기본 timeoutDuration을 6초로 연장
=> 🐛 bug [#337-gateway] TimeLimiter 기본 timeoutDuration을 6초로 연장
